### ISSUE TITLE
Edit Example 3 in chapter 6.1.4

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML3.0-GML-Encoding#14]
The text says that the building solid references the polygons of the boundary surfaces of the installation, but that these references are only optional. However, in this example the references are mandatory to have a closed (watertight) solid geometry.

Also note that the BuildingInstallation has a gml:MultiSurface in the CityGML 3 example but not in the CityGML 2 example. Should be harmonized.

**Comment by 3DXScape** [comment]
Who can do the work?

**Comment by clausnagel** [comment]
done with 90f7be3632d990f144ea44b13c5ce9b1ffca1bf2
