### ISSUE TITLE
Fix Example 5 in chapter 6.1.4

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML3.0-GML-Encoding#15]
The [CityGML file referenced in this example](https://github.com/opengeospatial/CityGML3.0-GML-Encoding/tree/main/resources/examples/Transportation/Basic%20examples/Road_over_Bridge_CityGML3.0_LOD2_with_CityObjectRelations.gml) uses "equal" as relation type. However, it must be "shared" according to Req. 5.

Same is true for Example 6 and 10.

**Comment by TatjanaKutzner** [comment]
I changed the files.
