### ISSUE TITLE
Provide UML and ShapeChange config for deriving the XSDs

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML3.0-GML-Encoding#16]

**Comment by 3DXScape** [comment]
Yes. Who will add? Where?

**Comment by TatjanaKutzner** [comment]
The ShapeChange config file is there, it's in the "standard" folder. But that's probably not the appropriate place. 
How about a subfolder "encoding" in "resources"? There we can provide the resources required for the encoding.
This then also includes the UML Implementation Model we mention in Annex G.

I will do this.

**Comment by clausnagel** [comment]
Thanks, @TatjanaKutzner, sounds like a good approach. And then we could also reference the "encoding" folder from Annex G, so that users can directly access it from the specification document.

**Comment by 3DXScape** [comment]
Should be a link to the encoding repo. Tatjana will finish and close issue.

**Comment by TatjanaKutzner** [comment]
Done.

The Implementation Model implements now also this issue: https://github.com/opengeospatial/CityGML-3.0Encodings/issues/54
In this way, users can now use ShapeChange version 2.11 or later for deriving the XSDs themselves. There is no longer the need for providing our own adapted ShapeChange implementation.

**Comment by clausnagel** [comment]
Nice work, @TatjanaKutzner. This is great!
