### ISSUE TITLE
Req. 27 B is redundant

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML3.0-GML-Encoding#17]
According to the `dynamizer.xsd` the element `attributeRef` of the type `DynamizerType` is mandatory and must be provided. According to Req. 25, all instance documents using concepts of the Dynamizer module must conform to `dynamizer.xsd`. Thus, `attributeRef` must be provided.

Req. 27 B only repeats this fact and, thus, should be removed.

**Comment by 3DXScape** [comment]
I agree that the schema file makes this redundant. Who will remove if we all agree?

**Comment by clausnagel** [comment]
Sorry, I misread the requirement 27 B. It does not say that `attributeRef` must be present but that the attribute referenced by `attributeRef` must be present. This requirement cannot be expressed in XML Schema, of course. So, it's not redundant and we must keep 27 B. Closing this issue.
