### ISSUE TITLE
Do we need Req. 6?

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML3.0-GML-Encoding#20]
Requirement 6 is about referencing features using XLinks. The requirement says that a feature must be stored inline its "natural aggregation" and only be referenced per XLink from "alternative aggregations" when needed. The default example for an alternative aggregation are CityObjectGroups. The members of a CityObjectGroup should not be stored inline the CityObjectGroup but only be referenced using an XLink.

I think this requirement is already implemented in the XML schemas wherever needed. For example, the `groupParent` and `groupMember` properties of a CityObjectGroup are defined such that they only allow XLinks but not storing an element inline. The same is true for similar properties in the Core, Dynamizer, and Versioning modules.

So, since this rule is implemented in the XML schemas and the base requirement for all instance documents is that they must validate against the XML schemas, this seems to make Req. 6 obsolet, doesn't it?! 

I also think that examples 8 and 9 in chapter 6.1.4 are not valid examples for this requirement. Within one and the same top-level feature, it shouldn't make a difference where a sub-feature is stored as long as it is reused using XLinks instead of making local copies. If, however, we really want to enforce using XLinks for certain properties (e.g. referencing rooms from a storey as in example 8), then I think this should also be implemented in the XML schema instead of letting a user guess what the "natural" and "alternative" aggregation is.

For similar reasons I don't see the "Exception" example in chapter 6.1.4 as exception of Req. 6.

**Comment by 3DXScape** [comment]
I agree with the first part, but what should we do with

> I also think that examples 8 and 9 in chapter 6.1.4 are not valid examples for this requirement. Within one and the same top-level feature, it shouldn't make a difference where a sub-feature is stored as long as it is reused using XLinks instead of making local copies. If, however, we really want to enforce using XLinks for certain properties (e.g. referencing rooms from a storey as in example 8), then I think this should also be implemented in the XML schema instead of letting a user guess what the "natural" and "alternative" aggregation is.

**Comment by 3DXScape** [comment]
Regroup examples 8 and 9 below 10. Add heading about referencing features rather than natural aggregations, citing the road intersection example. Claus will update text and close when done.

**Comment by clausnagel** [comment]
fixed with #27
