### ISSUE TITLE
The title of the main README file is confusing

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/CityGML3.0-GML-Encoding#25]
The title is currently "CityGML 3.0 GML 3.2 Encoding", which is confusing because it can be read to mean that this is:

* Version 3.2 of the CityGML 3.0 GML Encoding
* The GML 3.2 encoding for CityGML 3.0

I suggest changing the title to either of:

* "CityGML 3.0 GML 3.2 Encoding, Version 1.0"
* "CityGML 3.0 GML Encoding 1.0"
* "CityGML 3.0 GML Encoding, Version 1.0"

**Comment by ghobona** [comment]
Please note that the suggestions listed above are only about the README file and not about the Standards document.

**Comment by 3DXScape** [comment]
Agreed and changed
