### ISSUE TITLE
Version metadata attribute in the code list examples

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML3.0-GML-Encoding#28]
Based on https://github.com/opengeospatial/CityGML-3.0Encodings/issues/56 the metadata attribute "version" should define the version of the code list. Currently, however, it defines the version of CityGML. The CityGML version itself can be identified from the namespace provided (at least that's how I remember our discussions).
Thus, in the XML and CSV example the value should be changed from 3.0 to 1.0.
And to avoid confusion in the CSV example, I suggest to change there the attribute name from "CityGML_Version" to "Version".

**Comment by 3DXScape** [comment]
I made these changes.
