### ISSUE TITLE
Fix figures in Annex G

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/CityGML3.0-GML-Encoding#29]
Some of the Figures in Annex G have text overwriting other elements in the diagrams. Please see attached.

<img width="1092" alt="Screenshot 2023-04-04 at 22 32 13" src="https://user-images.githubusercontent.com/18121038/229928257-2a65ee43-ce7d-44d8-8c8d-c16ce4bfba79.png">

**Comment by TatjanaKutzner** [comment]
Done. I improved the layout. See commit 926e639.
