### ISSUE TITLE
Link on resources/examples/README.md doesn't work

### ISSUE THREAD

**Issue by maynouf** [opengeospatial/CityGML3.0-GML-Encoding#31]
When clicking on the link in `resources/examples/README.md`, the link to `https://github.com/opengeospatial/CityGML3.0-GML-Encoding/blob/main/resources/Examples/_Examples%20covering%20several%20modules` returns a 404 error:

```404 - page not found
The main branch of CityGML3.0-GML-Encoding does not contain the path resources/Examples/_Examples%20covering%20several%20modules
```

At a quick glance, perhaps the use of the upper case in `Examples` or the spaces may be at fault. Might do a PR later (I'll check the guidelines), just found it relevant enough to report it.

**Comment by TatjanaKutzner** [comment]
Thank you for the information. Yes, the capital E needs to be a small e. I corrected it directly in the file. The link works now again.
