### ISSUE TITLE
Public Review Comment from Heidi Vanparys: Various Editorial and Structural

### ISSUE THREAD

**Issue by 3DXScape** [opengeospatial/CityGML3.0-GML-Encoding#6]
**Received from Heidi Vanparys, Danish Agency for Data Supply and Infrastructure** 

PART A

1. Evaluator:
       Heidi Vanparys ([hevan@sdfi.dk](mailto:hevan@sdfi.dk)), Danish Agency for Data Supply and Infrastructure

2. Submission: 21-006, OGC City Geography Markup Language (CityGML) Part 2: GML Encoding Standard

PART B

---
- [x] **Comment 1**

1. Requirement: -

2. Implementation Specification Section number: Chapter 3 References.

3. Criticality: Editorial

4. Comments/justifications for changes: This section should only contain normative references, that is specifications that . E.g. D2.8.III.2 Data Specification on Buildings – Technical Guidelines is not a normative references, it is only used as source of some definitions, it is not required for CityGML instance documents to conform to D2.8.III.2. This reference should be placed in the bibliography. Double-check whether the other references belong in the section 3 or in the bibliography. E.g. a CityGML instance document cannot conform to ISO 19103, etc.

---
- [x] **Comment 2**

1. Requirement: -

2. Implementation Specification Section number: Chapter 3 References.

3. Criticality: Editorial

4. Comments/justifications for changes: The last reference refers to an outdated version of GML 3.2. It should be: OGC. OGC 07-036r1, OpenGIS® Geography Markup Language (GML) Encoding Standard v3.2.2. Any references to OGC 07-036 in the text should be changed to OGC 07-036r1.

---
- [x] **Comment 3**

1. Requirement: -

2. Implementation Specification Section number: Chapter 6.

3. Criticality: Minor

4. Comments/justifications for changes: The target type of the requirements classes is defined very broad: "Implementation". This should be much more precise. In Chapter 2 "Implementations of hte CityGML 3.0 Conceptual Model using GML encodings" is used.

---
- [x] **Comment 4**

1. Requirement: 1, /req/global/gml

2. Implementation Specification Section number: 6.1.1. Use of GML 3.2

3. Criticality: Editorial

4. Comments/justifications for changes: The text says "They may use certain aspects of CityGML 3.3"; probably "They may use certain aspects of GML 3.3" is meant.

---
- [x] **Comment 5**

1. Requirement: -

2. Implementation Specification Section number: Listing 1. Use of the identity attributes in CityGML 3 instance documents.

3. Criticality: Minor

4. Comments/justifications for changes: The example does not illustrate what is described in the text above, as the values gml:id and gml:identifier are the same, "B1020". When looking at section B.3, it seems that "B1020_t1" should be used as value for gml:id.

---
- [x] **Comment 6**

1. Requirement: -

2. Implementation Specification Section number: Chapter 7. Media types

3. Criticality: Minor

4. Comments/justifications for changes: There is a recommendation "hidden" in the text, should it be formatted as a recommendation and be given a URI? Similary to Recommendation 1 /rec/core/crs?

---
- [x] **Comment 7**

1. Requirement: -

2. Implementation Specification Section number: B.3. Versioning Examples

3. Criticality: Minor

4. Comments/justifications for changes: There are requirements hidden in the text, using the "shall" wording, and being described as "rules", e.g. When only the top-level feature changes, a new version of the top-level feature SHALL be created which receives a new gml:id. Are these rules requirements or not? The document should be updated accordingly. When the rules are not formal requirements, MUST instead of SHALL could e.g. be used? There should also be text that explains this.

**Comment by 3DXScape** [comment]
Resolution: Accept all suggested changes. Implement last comment by change of language.

**Comment by TatjanaKutzner** [comment]
Regarding comment 5: Originally the gml:id was given as "B1020_t1". Based on a comment from Claus saying that gml:id and identifier should be identical in the default case, we changed the gml:id to "B1020".
@clausnagel: It is fine for you to change this back to "B1020_t1"?

**Comment by 3DXScape** [comment]
Tatjana volunteered to make these 1, 2, 3, and 5 changes. For 5, accepting the comment and adding a statement that the id and identifier might be the same - implementation-dependent - for example, in a first version.

**Comment by clausnagel** [comment]
> It is fine for you to change this back to "B1020_t1"?

I checked the text in 6.1.2 again and it clearly says that "the values of the gml:id and the gml:identifier might also be identical, for example, when only a first version of the object exists".

Since Listing 1 is the first listing in the entire document and chapter 6.1.2 is not about versioning in the first place, I would rather keep "B1020" as gml:id here. The use of "B1020_t1" as value for the gml:id in the context of versioning should then be discussed and exemplified in annex B.3.

**Comment by 3DXScape** [comment]
OK Mostly done, but there is now a little work to do here if we accept Claus' suggestion above.

**Comment by 3DXScape** [comment]
Comment 5: Will retain B1020 identifier. Adding a comment in XML example to indicate that need not be same as ID and improving definition of identifier in table with text:

**Specifies the global identifier of the feature. The identifier must be globally valid, unique and identical over different feature versions.**

Notes: 
ID is a valid identifier
Identifier is globally unique and identical across versions.

They may be identical in a single or first version.




Claus will update and close.

**Comment by clausnagel** [comment]
I added the improved definition of the gml:identifier with a31096e3780dda23ccdb9dc227658eaecd5b0a02.

For the example in Listing 1, we finally decided to accept Comment 5 and use `B1020_t1` as value for the gml:id and `B1020` as value for the gml:identifier. However, the justification for Comment 5 is not correct because the text clearly allows both values to be identical.
