### ISSUE TITLE
Abstract Test Suite Review

### ISSUE THREAD

**Issue by 3DXScape** [opengeospatial/CityGML3.0-GML-Encoding#9]
Check correspondence between requirements and tests. Look at test methods and suggest better or different if appropriate.

**Comment by 3DXScape** [comment]
Done

**Comment by 3DXScape** [comment]
Claus will review once more.

**Comment by clausnagel** [comment]
Reviewed and opened PR #19

**Comment by 3DXScape** [comment]
We can close this now since anything remaining can be tracked via the PR 19.
